# define 5 sets of joint angles for the youbot arm

forward_kinematics:
  joint_angles:
    set0: [0.5, 0.5, -1.0, 0.3, 1.0]
    set1: [2.0, 1.0, -2.0, 1.0, 2.0]
    set2: [3.0, 1.0, -3.0, 1.5, 3.0]
    set3: [4.0, 2.0, -4.0, 2.0, 4.0]
    set4: [5.0, 2.0, -5.0, 3.0, 5.0]